apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: nextcloud
spec:
  secretName: nextcloud-tls-secret
  issuerRef:
    name: nginx-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nextcloud.kube.home