---
# tasks file for pi configurataion

- name: Change hostname
  lineinfile:
    backup: yes
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: "127.0.1.1\t{{ pi_hostname }}"
  tags: config, hostname

- name: Change static ip
  lineinfile:
    backup: yes
    path: /etc/dhcpcd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^interface eth0", line: "interface eth0" }
    - { regexp: "^static ip_address=", line: "static ip_address={{ pi_ip_addr }}" }
    - { regexp: "^static routers=", line: "static routers={{ router_ip_addr }}" }
  tags: config, host_addr

- name: Enable container features for k3s
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    regexp: "^.*"
    line: 'console=serial0,115200 console=tty1 root=PARTUUID=89a734e1-02 rootfstype=ext4 fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  tags: config, container_features, k3s

- name: Switch Debian firewall to legacy config
  ansible.builtin.shell: update-alternatives --set iptables /usr/sbin/iptables-legacy
  ansible.builtin.shell: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  tags: config, firewall, k3s