---
# tasks file for pi configurataion

- name: Change hostname
  lineinfile:
    backup: yes
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: "127.0.1.1\t{{ pi_hostname }}"
  tags: config, hostname

- name: Change static ip
  lineinfile:
    backup: yes
    path: /etc/dhcpcd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^interface eth0", line: "interface eth0" }
    - { regexp: "^static ip_address=", line: "static ip_address={{ pi_ip_addr }}" }
    - { regexp: "^static routers=", line: "static routers={{ router_ip_addr }}" }
  tags: config, host_addr

