- name: Install Helm
  shell: | 
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    apt-get install apt-transport-https --yes
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    apt-get update
    apt-get install helm
  tags: helm
  
- name: Add Helm repo
  kubernetes.core.helm_repository:
    repo_name: stable
    repo_url: stable https://charts.helm.sh/stable
    repo_state: present
  tags: helm

- name: Add nginx Helm repo
  kubernetes.core.helm_repository:
    repo_name: nginx-stable
    repo_url: https://helm.nginx.com/stable
    repo_state: present
  tags: helm, nginx

- name: Install Metallb
  kubernetes.core.helm:
    update_repo_cache: true
    name: metallb
    namespace: kube-system
    chart_ref: stable/metallb
    values:
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses: 
          - 192.168.0.240-192.168.0.250
  tags: metallb
    
- name: Install nginx
  kubernetes.core.helm:
    update_repo_cache: true
    name: nginx-ingress
    namespace: kube-system
    create_namespace: true
    chart_ref: nginx-stable/nginx-ingress
  tags: nginx


# - name: Install Metallb
#   shell: |
#     helm repo add stable https://charts.helm.sh/stable
#     helm install metallb stable/metallb --namespace kube-system \
#     --set configInline.address-pools[0].name=default \
#     --set configInline.address-pools[0].protocol=layer2 \
#     --set configInline.address-pools[0].addresses[0]=192.168.0.240-192.168.0.250
#   tags: metallb

# - name: Install nginx
#   shell: |
#     helm repo add nginx-stable https://helm.nginx.com/stable 
#     helm repo update
#     helm install nginx-ingress nginx-stable/nginx-ingress --namespace kube-system
#   tags: nginx
