- name: Install Helm
  shell: | 
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    apt-get install apt-transport-https --yes
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    apt-get update
    apt-get install helm
  tags: helm
  
- name: Add Helm repo
  kubernetes.core.helm_repository:
    repo_name: stable
    repo_url: stable https://charts.helm.sh/stable
    repo_state: present
  tags: helm

- name: Install Metallb
  kubernetes.core.helm:
    update_repo_cache: true
    name: metallb
    namespace: kube-system
    chart_ref: stable/metallb
    values:
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses: 
          - 192.168.0.240-192.168.0.250
  tags: metallb
    
- name: Add nginx Helm repo
  kubernetes.core.helm_repository:
    repo_name: nginx-stable
    repo_url: https://helm.nginx.com/stable
    repo_state: present
  tags: helm, nginx

- name: Install nginx
  kubernetes.core.helm:
    update_repo_cache: true
    name: nginx-ingress
    namespace: kube-system
    create_namespace: true
    chart_ref: nginx-stable/nginx-ingress
  tags: nginx

- name: Add kubeseal Helm repo
  kubernetes.core.helm_repository:
    repo_name: sealed-secrets
    repo_url: https://bitnami-labs.github.io/sealed-secrets
    repo_state: present
  tags: sealed-secrets

- name: Install kubeseal server-side controller to encrypt secrets
  kubernetes.core.helm:
    update_repo_cache: true
    name: sealed-secrets
    namespace: kube-system
    #helm create_namespace: true
    chart_ref: sealed-secrets/sealed-secrets
  tags: sealed-secrets

- name: Download kubeseal client-side CLI binary
  ansible.builtin.get_url:
    url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.2/kubeseal-0.18.2-linux-arm64.tar.gz
    dest: /home/isaac/
  tags: sealed-secrets, kubeseal

- name: Extract kubeseal binary
  unarchive:
    src: /home/isaac/kubeseal-0.18.2-linux-arm64.tar.gz
    dest: /home/isaac/
    exclude:
      - LICENSE
      - README.md
  tags: sealed-secrets, kubeseal

- name: Install kubeseal binary
  shell: install -m 755 /home/isaac/kubeseal /usr/local/bin/kubeseal
  tags: sealed-secrets, kubeseal

- name: Delete kubeseal tar
  file:
    path: /home/isaac/kubeseal*
    state: absent
  tags: sealed-secrets, kubeseal