- name: Enable container features for k3s
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    regexp: "^.*"
    line: 'console=serial0,115200 console=tty1 root=PARTUUID=89a734e1-02 rootfstype=ext4 fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  tags: container_features, k3s

- name: Switch Debian firewall to legacy config
  shell: |
    update-alternatives --set iptables /usr/sbin/iptables-legacy
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  tags: firewall, k3s

- name: K3s pre-config
  shell: |
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC=" --no-deploy servicelb --no-deploy traefik"
  tags: k3s

- name: Download & Install k3s
  shell: curl -sfL https://get.k3s.io | sh -
  tags: k3s

