- name: Enable container features for k3s
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    regexp: "^.*"
    line: 'console=serial0,115200 console=tty1 root=PARTUUID=89a734e1-02 rootfstype=ext4 fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  tags: container_features, k3s

- name: Switch Debian firewall to legacy config
  shell: update-alternatives --set iptables /usr/sbin/iptables-legacy
  shell: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  tags: firewall, k3s

- name: K3s pre-config
  shell: |
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC=" --no-deploy servicelb --no-deploy traefik"
  tags: k3s

- name: Download & Install k3s
  shell: curl -sfL https://get.k3s.io | sh -
  tags: k3s

- name: Install Helm
  shell: | 
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    apt-get install apt-transport-https --yes
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    apt-get update
    apt-get install helm
  tags: helm