apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-ssd
  namespace: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
