apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-ssd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: /mnt/ssd/media
---
