- name: Create nextcloud namespace
  kubernetes.core.k8s:
    name: nextcloud
    kind: Namespace
    state: present
  tags: nextcloud

- name: Create nextcloud directory for PV
  file:
    path: /mnt/ssd/nextcloud
    state: directory
  tags: nextcloud

- name: Create PersistentVolume
  kubernetes.core.k8s:
    src: nextcloud-persistentvolume.yml
    state: present
  tags: nextcloud

- name: Create PersistentVolumeClaim
  kubernetes.core.k8s:
    src: nextcloud-persistentvolumeclaim.yml
    state: present
  tags: nextcloud

- name: Configure nextcloud Helm repository
  kubernetes.core.helm_repository:
    name: nextcloud
    url: https://nextcloud.github.io/helm/
    state: present
  tags: nextcloud

- name: Install nextcloud
  kubernetes.core.helm:
    update_repo_cache: true
    name: nextcloud
    namespace: nextcloud
    chart_ref: nextcloud/nextcloud
    values_files: /home/isaac/ansible/k3s-install/roles/nextcloud/files/nextcloud-values.yml
    #atomic: true cannot use this, install throws error which causes the atomic setting to exec
    release_state: present
  tags: nextcloud

- name: Create certificate object
  kubernetes.core.k8s:
    src: nextcloud-cert.yml
    state: present
  tags: nextcloud

- name: Deploy nextcloud ingress
  kubernetes.core.k8s:
    src: nextcloud-ingress.yml
    state: present
  tags: nextcloud